### ISSUE TITLE
Support :class="..." in vue template

### ISSUE THREAD

**Issue by ram-you** [gencer/SCSS-Everywhere#60]
Hi, worked perfectly inside class="..." in vue template but not inside **:class**="..."
Thank you.

**Comment by gencer** [comment]
Hey @ram-you.

I just and a look at Vue's `:class` and it seems it is not a simple string but conditional syntax's used there. Like:

```vue
:class="{ 'klass': klass }"
```

I am not sure how should we complete here because all we do in here is `regex`. If I add escape characters will this be enough? For example:

# v1.7.8
[html-slim-scss-css-class-completion-1.7.8.zip](https://github.com/gencer/SCSS-Everywhere/files/5615518/html-slim-scss-css-class-completion-1.7.8.zip)

Can you test this version and let me know?

**Comment by ram-you** [comment]
@gencer  Thank you very much. **v1.7.8** works perfectly.

**Comment by gencer** [comment]
I'm glad to hear that. I will revisit this issue at a later time for a better `regex` pattern match. Because, currently its a bit hacky.
